flat_split_combine.Rmd:
  path: dev/flat_split_combine.Rmd
  state: active
  R:
  - R/combine_tbl_to_file.R
  - R/split_to_tbl.R
  tests:
  - tests/testthat/test-split_to_tbl.R
  - tests/testthat/test-split_headers_from_text.R
  - tests/testthat/test-special-rmd-formats.R
  - tests/testthat/test-combine_tbl_to_file.R
  vignettes: vignettes/z-split-a-rmd-or-qmd-file-into-a-tibble-and-vice-versa.Rmd
  inflate:
    flat_file: dev/flat_split_combine.Rmd
    vignette_name: z-Split a Rmd or Qmd file into a tibble and vice-versa
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
keep:
  path: keep
  state: active
  R: R/globals.R
  tests: []
  vignettes: []
